# Numpy Operations

## Element-wise array-array operations
When we add, subtract, multiply and divide arrays with each other, the default behaviour is element-wise operations:

## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

In [48]:
import numpy as np
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

1) Array with array

In [49]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [51]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

C:\Users\chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [54]:
1/0

ZeroDivisionError: division by zero

In [56]:
# Also warning, but not an error instead infinity
1/arr

C:\Users\chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

2) Array with scalars

In [57]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [58]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91])

In [59]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

Exercise: Use x = np.random.random((5,3)); y=np.random.random((5,3))

In [60]:
np.random.seed(345)
x = np.random.random((5,3))
np.random.seed(567)
y = np.random.random((5,3))

In [61]:
x

array([[0.37092674, 0.66488423, 0.496658  ],
       [0.60207905, 0.24418494, 0.49474806],
       [0.71054041, 0.45139238, 0.04703766],
       [0.53097772, 0.5530579 , 0.11443496],
       [0.24547424, 0.8367019 , 0.90579506]])

In [62]:
y

array([[0.30478164, 0.95303297, 0.96470869],
       [0.34376214, 0.99388576, 0.30207403],
       [0.87623109, 0.70564267, 0.68115012],
       [0.54826595, 0.57399478, 0.930455  ],
       [0.60177031, 0.54688225, 0.92238086]])

In [63]:
x[0, :]

array([0.37092674, 0.66488423, 0.496658  ])

In [64]:
# Select the second column from array a2d
x[:, 1]

array([0.66488423, 0.24418494, 0.45139238, 0.5530579 , 0.8367019 ])

In [65]:
x + y

array([[0.67570839, 1.6179172 , 1.4613667 ],
       [0.94584118, 1.23807071, 0.79682209],
       [1.58677151, 1.15703505, 0.72818778],
       [1.07924367, 1.12705269, 1.04488996],
       [0.84724456, 1.38358415, 1.82817592]])

In [66]:
x - y

array([[ 0.0661451 , -0.28814874, -0.46805069],
       [ 0.25831691, -0.74970082,  0.19267403],
       [-0.16569068, -0.25425029, -0.63411246],
       [-0.01728824, -0.02093688, -0.81602004],
       [-0.35629607,  0.28981965, -0.0165858 ]])

In [67]:
x * y

array([[0.11305166, 0.63365659, 0.4791303 ],
       [0.20697198, 0.24269194, 0.14945054],
       [0.6225976 , 0.31852172, 0.03203971],
       [0.291117  , 0.31745235, 0.10647658],
       [0.14771911, 0.45757742, 0.83548803]])

In [68]:
x / y

array([[1.21702455, 0.69765081, 0.51482692],
       [1.75144085, 0.24568713, 1.63783713],
       [0.81090527, 0.63968975, 0.06905623],
       [0.96846742, 0.96352427, 0.12298818],
       [0.40792016, 1.52994891, 0.98201849]])

In [69]:
from numpy.random import randint

In [70]:
randint(3,6)

5

## Universal array functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [71]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [73]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [74]:
np.max(arr) #same as arr.max()

9

In [75]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [76]:
np.log(arr)

C:\Users\chris\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

#### Note: The course materials are developed mainly based on personal experience and contributions from the Python learning community
Referred book: Learning Python, 5ht Edition by Mark Lutz