# NumPy BreakoutGroupExercises - Solutions

#### Import NumPy as np

In [85]:
import numpy as np

#### 1. Create an array of 8 zeros 

In [86]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

#### 2. Create an array of 8 ones

In [87]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

#### 3. Create an array of 8 fives

In [88]:
np.ones(8) * 5

array([5., 5., 5., 5., 5., 5., 5., 5.])

In [89]:
np.zeros(8) + 5

array([5., 5., 5., 5., 5., 5., 5., 5.])

#### 4. Create an array of the integers from 0 to 50

In [90]:
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

#### 5. Create an array of all the even integers from 0 to 50

In [91]:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

#### 6. Create a 4x4 matrix with values ranging from 0 to 15

In [93]:
np.arange(16).reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 7. Create a 4x4 identity matrix

In [94]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### 8. Use NumPy to generate 3x3 random numbers between 0 and 1

In [97]:
np.random.rand(3,3)

array([[0.0707183 , 0.26877358, 0.96061432],
       [0.42363044, 0.9817718 , 0.48848687],
       [0.7302583 , 0.16634504, 0.68942287]])

#### 9. Use NumPy to generate an array of 20 random numbers sampled from a standard normal distribution

In [98]:
np.random.randn(20)

array([-0.01084577,  1.24826469,  0.38090452, -0.38703834,  0.72291564,
        0.6726398 , -0.05986667, -0.40538091,  0.93224637, -0.13782748,
       -0.23348985, -0.45945263, -1.25972118, -0.57322412, -0.89930858,
        0.98005293, -0.34270796,  0.53276312, -0.24161947,  0.8302753 ])

#### 10. Create the following matrix:

In [99]:
np.arange(1,51).reshape(5,10) / 100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ]])

In [100]:
np.linspace(0.01,1,50).reshape(5,10)

array([[0.01      , 0.03020408, 0.05040816, 0.07061224, 0.09081633,
        0.11102041, 0.13122449, 0.15142857, 0.17163265, 0.19183673],
       [0.21204082, 0.2322449 , 0.25244898, 0.27265306, 0.29285714,
        0.31306122, 0.33326531, 0.35346939, 0.37367347, 0.39387755],
       [0.41408163, 0.43428571, 0.4544898 , 0.47469388, 0.49489796,
        0.51510204, 0.53530612, 0.5555102 , 0.57571429, 0.59591837],
       [0.61612245, 0.63632653, 0.65653061, 0.67673469, 0.69693878,
        0.71714286, 0.73734694, 0.75755102, 0.7777551 , 0.79795918],
       [0.81816327, 0.83836735, 0.85857143, 0.87877551, 0.89897959,
        0.91918367, 0.93938776, 0.95959184, 0.97979592, 1.        ]])

#### 11. Create an array of 20 linearly spaced points between 0 and 1:

In [101]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### 12. Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [102]:
mat = np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [103]:
# Solution

In [104]:
mat[2:,1:]

array([[10, 11, 12],
       [14, 15, 16]])

In [105]:
# Solution

In [106]:
mat[2:,2]

array([11, 15])

In [107]:
# Solution

In [108]:
mat[:3,1:2]

array([[ 2],
       [ 6],
       [10]])

In [109]:
# Solution

In [110]:
mat[3,:]

array([13, 14, 15, 16])

In [111]:
mat[-1,:]

array([13, 14, 15, 16])

In [112]:
# Solution

In [113]:
mat[1:5,:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [114]:
# Solution

In [115]:
mat[:,3]

array([ 4,  8, 12, 16])

In [ ]:
# Solution

In [116]:
mat[-1:]

array([[13, 14, 15, 16]])

#### 13. Get the sum of all the values in mat

In [117]:
mat.sum()

136

In [118]:
np.sum(mat)

136

#### 14. Get the standard deviation of the values in mat

In [119]:
mat.std()

4.6097722286464435

In [120]:
np.std(mat)

4.6097722286464435

#### 15. Get the sum of all the columns in mat

In [121]:
mat.sum(axis=0)

array([28, 32, 36, 40])

In [122]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 16. Get the sum of all the columns in mat

In [123]:
mat.sum(axis=1)

array([10, 26, 42, 58])