## Copy in Python – Deep Copy and Shallow Copy

### Assignment - Shallow Copy:
When we perform an `assignment` in Python, it does not copy the object we assign. All it does is create bindings between a target and an object. But sometimes, we may need to change one Python copy without changing the other for a mutable collection.

In [1]:
a = [1,2,3,4]
c = a
c[3] = 5
a

[1, 2, 3, 5]

### Module Copy

The `module copy` in Python. It has the following members:

- 1). `copy.copy(x)`: This returns a shallow copy of x.

- 2). `copy.deepcopy(x)`: This returns a deep copy of x.

#### 1). Deep Copy
When a deep copy in Python creates a new object, it inserts into the new object copies of the objects in the original object. In other words, it copies an object into another. This means any changes we make to the copy do not reflect in the original.


#### Deep Copy Example: Let’s try implementing this in Python. We use the deepcopy() function.

In [25]:
import copy
list1=[1,3,[7,4],6]
list2=copy.deepcopy(list1) # Making a deep copy
list1

[1, 3, [7, 4], 6]

In [26]:
list2

[1, 3, [7, 4], 6]

In [27]:
# Have a look at Python Syntax and Semantics

list2[2][0]=5 #Modifying the element at index 2,0

In [28]:
list1

[1, 3, [7, 4], 6]

In [29]:
list2
[1, 3, [5, 4], 6]

[1, 3, [5, 4], 6]

#### As you can see, this `deepcopy()` did not change anything for the original object.

#### Problems with Python Deep Copy

- It is possible that recursive objects cause a recursive loop; these are compound objects that directly or indirectly reference themselves.

- It is possible that a deep copy may copy too much.

To deal with these problems, deepcopy():

- Keeps a memo dictionary of objects is copied during the current copying pass.

- Allows user-defined classes to override the copying operation or the copied component set.


#### 2). Shallow Copy
With a Shallow Copy in Python, we create a new object of which we recursively put copies of objects into the original. In other words, we copy a reference of an object into another. Any changes we make to the copy do reflect in the original.


In [30]:
# Do you know about Python Function Arguments
# Let’s implement this with Python. We’ll use the copy() function.
import copy
list1=[1,3,[7,4],6]
list2=copy.copy(list1) #Making a shallow copy


In [31]:
list1

[1, 3, [7, 4], 6]

In [32]:
list2

[1, 3, [7, 4], 6]

In [33]:
list2[2][0]=5 #Modifying the element at index 2,0
list1

[1, 3, [5, 4], 6]

In [34]:
list2  # It is apparent that making changes to a shallow copy does change the original object.

[1, 3, [5, 4], 6]

In [35]:
# Shallow Copying Dictionaries: Let’s first create a dictionary in Shallow Copy in Python.
dict1={'a':1,'b':2,'c':[1,2,3]}
dict1

{'a': 1, 'b': 2, 'c': [1, 2, 3]}

In [36]:
# Now, we’ll make a copy of it. Let’s revise the Python Built-in Function
dict2=dict1.copy()
dict2

{'a': 1, 'b': 2, 'c': [1, 2, 3]}

In [37]:
# Finally, we’ll append a new element to this.
dict2['c'].append(7)
dict1


{'a': 1, 'b': 2, 'c': [1, 2, 3, 7]}

In [38]:
dict2


{'a': 1, 'b': 2, 'c': [1, 2, 3, 7]}

In [39]:
# Other ways to create a shallow copy of a dictionary are dict(dict1) and copy.copy(dict1). 
# As you can see, altering the mutable in the copy changed the original too. 
# To prevent this, we can do a deep copy in Python.
import copy
dict1={'a':1,'b':2,'c':[1,2,3]}
dict2=copy.deepcopy(dict1)
dict2['c'].append(7)
dict1


{'a': 1, 'b': 2, 'c': [1, 2, 3]}

In [40]:
dict2

{'a': 1, 'b': 2, 'c': [1, 2, 3, 7]}

### NumPy copy() function - Deep Copy

In [42]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
A

array([[1, 2],
       [3, 4]])

In [44]:
C = np.copy(A)
C

array([[1, 2],
       [3, 4]])

In [45]:
C[0,0] = -5
C

array([[-5,  2],
       [ 3,  4]])

In [46]:
A

array([[1, 2],
       [3, 4]])